import time
import os
import random
import psutil
import sys
from traceback import print_tb
import curses

from colorama import init
init(strip=not sys.stdout.isatty())
from termcolor import cprint
from pyfiglet import figlet_format
from gc import is_finalized
from colorama import *
from datetime import datetime

init()

now = datetime.now()
os.system('cls' if os.name == 'nt' else 'clear')
print("                                                        starting..")
time.sleep(1.5)
os.system('cls' if os.name == 'nt' else 'clear')
time.sleep(0.1)
cprint(figlet_format("                        JxOS v 3 . 9", font='big'),
       'blue', attrs=['bold'])
time.sleep(0.1)
print("                                           By B0mba303 and infinitehate" + Style.RESET_ALL)
time.sleep(0.5)
print("")
print("Checking components:")
print("")
time.sleep(1)
print(Fore.LIGHTGREEN_EX + "Disk |  [OK]")
time.sleep(0.4)
print(Fore.LIGHTGREEN_EX + "RAM  |  [OK]")
time.sleep(0.3)
print(Fore.LIGHTGREEN_EX + "CPU  |  [OK]" + Style.RESET_ALL)
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + "GPU  |  [OK]" + Style.RESET_ALL)
print("")
time.sleep(1)
print("Your system will start successfully.")
time.sleep(0.01)
input("Press Enter to continue...")
time.sleep(0.01)
os.system('cls' if os.name == 'nt' else 'clear')
time.sleep(1)
print("Loading...")
time.sleep(0.5)
ram1 = "32mb"
rom1 = "100mb"
print("RAM:" + ram1)
time.sleep(0.1)
print("ROM:" + rom1)
time.sleep(0.1)
print("JxOS 3.9")
time.sleep(0.5)
os.system('cls' if os.name == 'nt' else 'clear')
time.sleep(0.1)
print(Fore.LIGHTGREEN_EX + " +===========================================+")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |                 JxOS info:                |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | You have a licensed version of the OS     |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | System version: 3.9                       |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " +-------------------------------------------+")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | YouTube channel of the main developer:    |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | https://www.youtube.com/@Imc-f8m          |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |                                           |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | Also helped:                              |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " | https://www.youtube.com/@ignatikklokov    |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " +===========================================+")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    Commands:                              |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    calc - calculator                      |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    info - information                     |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    cls - clear terminal                   |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    time - current time                    |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    date - current date                    |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    say - say in termina                   |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    writer/notepad - notepad               |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    shutdown/shut - end session            |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    cube - roll dice                       |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    reboot - reboot system                 |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    scull - show skull                     |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + ' |    random - give random number            |')
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    cpu - show CPU load                    |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " |    barchart - graph structure             |")
time.sleep(0.01)
print(Fore.LIGHTGREEN_EX + " +===========================================+" + Style.RESET_ALL)
while True:
    command1 = input("[JxOS] > ").strip()
    if command1 == "info":
        print(Fore.LIGHTGREEN_EX + " +===========================================+")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |                 JxOS info:                |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | You have a licensed version of the OS     |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | System version: 3.9                       |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " +===========================================+" + Style.RESET_ALL)
    elif command1 == "calc":
        calc1 = float (input("Enter first number:"))
        calc2 = float (input("Enter second number:"))
        calc3 = input("Select action (+, -, *, / ):")
        if calc3 == "+":
            answer1 = (calc1 + calc2)
            print(str(answer1))
            time.sleep(0.1)
        if calc3 == "-":
            answer1 = (calc1 - calc2)
            print(str(answer1))
            time.sleep(0.1)
        if calc3 == "*":
            answer1 = (calc1 * calc2)
            print(str(answer1))
            time.sleep(0.1)
        if calc3 == "/":
            answer1 = (calc1 / calc2)
            print(str(answer1))
            time.sleep(0.1)
    elif command1 == "help":
        print(Fore.LIGHTGREEN_EX + " +===========================================+")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |                 JxOS info:                |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | You have a licensed version of the OS     |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | System version: 3.9                       |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " +-------------------------------------------+")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | YouTube channel of the main developer:    |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | https://www.youtube.com/@Imc-f8m          |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |                                           |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | Also helped:                              |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " | https://www.youtube.com/@ignatikklokov    |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " +===========================================+")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    Commands:                              |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    calc - calculator                      |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    info - information                     |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    cls - clear terminal                   |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    time - current time                    |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    date - current date                    |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    say - say in termina                   |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    writer/notepad - notepad               |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    shutdown/shut - end session            |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    cube - roll dice                       |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    reboot - reboot system                 |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    scull - show skull                     |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + ' |    random - give random number            |')
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    cpu - show CPU load                    |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " |    barchart - graph structure             |")
        time.sleep(0.01)
        print(Fore.LIGHTGREEN_EX + " +===========================================+" + Style.RESET_ALL)

    elif command1 == "cls":
        os.system('cls' if os.name == 'nt' else 'clear')
    elif command1 == "time":
        print(Fore.YELLOW + f'{now:time: %H:%M}' + Style.RESET_ALL)
        time.sleep(0.01)
    elif command1 == "date":
        print(Fore.YELLOW + f'{now:date: %d.%m.%Y}' + Style.RESET_ALL)
        time.sleep(0.01)
    elif command1 == "notepad":
        os.system('cls' if os.name == 'nt' else 'clear')
        mod = input("write(1) or read(2)?: ")
        if mod == "1":
            os.system('cls' if os.name == 'nt' else 'clear')
            w11 = input()
            os.system('cls' if os.name == 'nt' else 'clear')
        if mod == "2":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(w11)
            time.sleep(0.1)
    elif command1 == "writer":
        os.system('cls' if os.name == 'nt' else 'clear')
        mod = input("write(1) or read(2)?: ")
        if mod == "1":
            os.system('cls' if os.name == 'nt' else 'clear')
            w11 = input()
            os.system('cls' if os.name == 'nt' else 'clear')
        if mod == "2":
            os.system('cls' if os.name == 'nt' else 'clear')
            print(w11)
            time.sleep(0.1)
    elif command1.find("say")!= -1:
        print(command1.split("say ") [1])
        time.sleep(0.1)
    elif command1 == "cube":
        print(random.randint(1, 6))
        time.sleep(0.1)
    elif command1 == "shutdown":
        os.system('cls' if os.name == 'nt' else 'clear')
        time.sleep(0.1)
        print("Goodbye!")
        time.sleep(1)
        exit()
    elif command1 == "shut":
        os.system('cls' if os.name == 'nt' else 'clear')
        time.sleep(0.1)
        print("Goodbye!")
        time.sleep(1)
        exit()
    elif command1 == "cpu":
        cpu_percent = psutil.cpu_percent(interval=1)
        print(Fore.LIGHTBLUE_EX + f"CPU load is: {cpu_percent}%" + Style.RESET_ALL)
    elif command1 == "barchart":
        data = list(map(int, input("Enter values separated by spaces (max height 30): ").split()))
        height = max(data)
        if height > 30:
            print(Fore.RED + 'Error' + Style.RESET_ALL)
            continue
        time.sleep(0.01)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("")

        WHITE = "\033[37m"
        YELLOW = "\033[33m"
        RESET = "\033[0m"

        for y in range(height, -1, -1):
            row = f"{WHITE}{y:^4}|  {RESET}"
            for x in range(len(data)):
                if data[x] >= y:
                    row += f"{YELLOW}███  {RESET}"
                else:
                    row += "     "
            print(row + "|")
            time.sleep(0.3)

        print(f"{WHITE}    +{'-' * (len(data) * 5)}{RESET}" + "--+")
        time.sleep(0.01)
    elif command1 == "reboot":
        os.system('cls' if os.name == 'nt' else 'clear')
        time.sleep(0.1)
        print("Restart system...")
        time.sleep(3)
        os.system(f"wt -F python code.py ")
        exit()
    elif command1 == "scull":
        print(Fore.RED + "░▄▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄░")
        time.sleep(0.1)
        print(" ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░████")
        time.sleep(0.1)
        print(" ▀███▄░░░░░░░░░░▄▄▄▄▄▄░░░░░░░░░░▄███▀")
        time.sleep(0.1)
        print(" ░░░▀██▄██▀░▄██▀▀▀▀▀▀▀▀██▄░▀██▄██▀░░░")
        time.sleep(0.1)
        print(" ░░░░███████▀▄▄▄▄▄██▄▄▄▄▄▀███████░░░░")
        time.sleep(0.1)
        print(" ░░░░█▀████████████████████████▀█░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░▀████████████████████▀░░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░██▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀███░░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░▀█░░▄▄██▄░░▄██▄▄░░███░░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░▀█░░█████░░█████░░████░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░░█▄░░▀▀▀░▄▄░▀▀▀░░▄████░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░░░██▄▄░░████░░▄▄██████░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░░▄████░░████░░████████░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░▄████▀█░░░░░░░░█▀█████░░░░░░░")
        time.sleep(0.1)
        print(" ░░░░▄█████▀█▄▀▀▀█▀▀█▀▀▀▄███████▄░░░░")
        time.sleep(0.1)
        print(" ░░▀▀▀▀▀░░░░░█▄░░▀░░▀░░▄█▀███░▀▀▀▀▀░░")
        time.sleep(0.1)
        print(" ░░░░░░░░░░░░░▀████████▀░░░▀▀░░░░░░░░")
        time.sleep(0.1)
        print(" ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░" + Style.RESET_ALL)
        print("")
        time.sleep(1)
    elif command1 == "10101":
        os.system('cls' if os.name == 'nt' else 'clear')
        print("░░░░░░░░░░░░░░░░░░░░░░░░░░")
        time.sleep(0.1)
        print("░░░░░░░░░░░░██░░░░░░░░░░░░")
        time.sleep(0.1)
        print("░░░░░░░░░░░░██░░░░░░░░░░░░")
        time.sleep(0.1)
        print("░░░░░░░░░░██████░░░░░░░░░░")
        time.sleep(0.1)
        print("░░░░░░░░░░░░░░░░░░░░░░░░░░")
        print("")
        time.sleep(1)
        os.system('cls' if os.name == 'nt' else 'clear')
    elif command1 == "random":
        random_number = random.randint(1, 999999999)
        print(random_number)

    else:
        print(Fore.RED + "Unknown command" + Style.RESET_ALL)
        time.sleep(0.1)
